version: 2
jobs:
  # build job omitted for brevity
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Where are we?
          command: ls -la
      - run:
          name: Deploy to S3
          command: aws s3 sync . s3://josephfinlayson.com --exclude \".git/*\" --exclude \"node_modules/*\"

workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          context: AWS
          filters:
            branches:
              only: master